/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hughj' at '1/3/17 8:47 PM' with Gradle 3.2.1
 *
 * @author hughj, @date 1/3/17 8:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
