/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hughj' at '12/4/16 10:38 AM' with Gradle 2.10
 *
 * @author hughj, @date 12/4/16 10:38 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
