/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'hughj' at '1/13/17 7:55 AM' with Gradle 3.2.1
 *
 * @author hughj, @date 1/13/17 7:55 AM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
