/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'hughj' at '1/13/17 7:55 AM' with Gradle 3.2.1
 *
 * @author hughj, @date 1/13/17 7:55 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
